### ISSUE TITLE
Support for Kaniko and ECR

### ISSUE THREAD

**Issue by pfiled** [devspace-cloud/devspace#1010]
It looks like the config.json for logging into the registry is built into the devspace client and updated every time the build pod is started, using whatever credentials are stored in the local docker client.

Kaniko support a login helper that will use AWS IAM roles to log into ECR.

https://github.com/GoogleContainerTools/kaniko#pushing-to-amazon-ecr

The contents of config.json are just:
> `{ "credsStore": "ecr-login" }`

Is it possible to add the ability to use that config.json, instead of a registry access key?

Thank you!

**Comment by FabianKramm** [comment]
@pfiled thanks for opening this issue! Yes we can do that to make the kaniko build more flexibel

**Comment by FabianKramm** [comment]
@pfiled are you aware of the `images.build.kaniko.pullSecret` option? This allows you to specify a custom pull secret that is bound to the kaniko pod, which could store your custom docker config. I'm not sure if we should implement or add something else since this would pretty much solve your problem.

**Comment by LukasGentele** [comment]
In case anyone else is looking for this: I added a small example on how to do this to the docs: https://devspace.sh/cli/docs/configuration/images/kaniko#pullsecret

Closing this for now. Feel free to reopen if there are still issues on how to solve this.
