### ISSUE TITLE
Host path still associated to service of deleted deployment in Network tab

### ISSUE THREAD

**Issue by jerlam06** [devspace-cloud/devspace#1080]
**What happened?**  
I created a new space and deployed a new app called 'app1' into it using 'devspace deploy'. Then I deployed another app called 'app2' and deleted the 'app1' with 'devspace remove deployment app1'. 
Once the app1 was deleted, the 'app1' service was still used for the host '/' in the Network tab of DevSpace Cloud.

**What did you expect to happen instead?**  
When a deployment gets deleted, its associated service should also be deleted in the Network tab.

**Local Environment:**  
- DevSpace Version: 4.12.2
- Operating System: linux
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: DevSpace Cloud

**Anything else we need to know?**  

/kind enhancement

**Comment by FabianKramm** [comment]
@jerlam06 thanks for opening this issue! In general, the underlying service should be deleted alongside the deployment if you select `yes` after the `Do you want to delete all deployment resources deployed?` question, however the recommended way to delete deployments and resources with devspace is via `devspace purge`. Does it work when you run `devspace purge` instead of `devspace remove deployment app1`?

**Comment by LukasGentele** [comment]
I think what he means is that the ingress will still reference the `serviceName` even after running `devspace purge` which has deleted the service already. But there is nothing we can do. That is standard Kubernetes behavior. There is no tight coupling between ingress and service and that is intentional. Closing this for now.
