### ISSUE TITLE
Cannot connect external cluster

### ISSUE THREAD

**Issue by 0x77dev** [devspace-cloud/devspace#1082]
**What happened?**  
```
[fatal]  check resource availability: discover server resources: unable to retrieve the complete list of ser
ver APIs: admission.certmanager.k8s.io/v1beta1: the server is currently unable to handle the request
```

**What did you expect to happen instead?**  
Connect external cluster

**How can we reproduce the bug?** (as minimally and precisely as possible)  
```console
 ~/P/@/core  ⎇ rbac $  devspace connect cluster                 7s < понедельник, 27 апреля 2020 г. 16:28:15
[warn]   There is a newer version of DevSpace: v4.12.2. Run `devspace upgrade` to upgrade to the newest version.


? Please enter a cluster name (e.g. my-cluster) handyai-main

? Which kube context do you want to use
 arn:aws:eks:eu-central-1:606350344667:cluster/handyai-main-eu-central-1
[fatal]  check resource availability: discover server resources: unable to retrieve the complete list of ser
ver APIs: admission.certmanager.k8s.io/v1beta1: the server is currently unable to handle the request
```

**Local Environment:**  
- DevSpace Version: [`devspace version 4.9.3`]
- Operating System: mac
- Deployment method: helm | kubectl apply

**Kubernetes Cluster:**  
- Cloud Provider: aws [EKS]
- Kubernetes Version:
```json
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480
e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:
"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@0x77dev thanks for reporting this issue! The problem is that your cluster apiservices (the apiservice `admission.certmanager.k8s.io`) cannot be discovered, which is why devspace fails, you can verify this via `kubectl get apiservices`. Devspace does an initial cluster check before connecting a cluster and if that fails the cluster connect fails otherwise tools such as helm cannot be used in the cluster since they rely on api resource discovery. I suspect that you have a faulty apiservice (which can be deleted via `kubectl delete apiservice admission.certmanager.k8s.io`) that needs to be fixed before you can connect the cluster. As soon as all apiservices are Available in `kubectl get apiservices` connecting a cluster should work.

**Comment by 0x77dev** [comment]
Yeah, so I've just deleted cert manager, that's fixed this problem.
