### ISSUE TITLE
Kaniko doesn't work under loft

### ISSUE THREAD

**Issue by abh** [devspace-cloud/devspace#1126]
When using loft there's a no default resource limits configured, so kaniko fails with an error that resource limits aren't specified.  If devspace set (or had options to configure) limits on kaniko this would work.

**Comment by FabianKramm** [comment]
@abh thanks for opening this issue! In general, the recommended approach here is to create a limit range resource(https://kubernetes.io/docs/concepts/policy/limit-range/) in the namespace (can be done automatically in loft via space templates on space create) that will automatically set the resource limits based on your configuration if they are not specified.  

Besides from that approach, we can also add an option to specify resource limits, since it might be helpful to restrict the kaniko pod in certain circumstances, so I'll flag this as a new feature.

**Comment by abh** [comment]
@FabianKramm Thanks!  I couldn't get the template feature in loft to work so I added the LimitRange manually with an admin account on the cluster.

I opened this issue for the use case you mentioned of needing different resources than the default.

**Comment by FabianKramm** [comment]
@abh implemented in v4.14.0
