### ISSUE TITLE
Specify Kubernetes context in devspace.yaml

### ISSUE THREAD

**Issue by mnpenner** [devspace-cloud/devspace#1147]
**Is your feature request related to a problem?**  
Yes

**Which solution do you suggest?**  
Allow me to specify which Kubernetes context to use in `devspace.yaml`. 

Maybe under `deployments[*].kubectl.context`? Or a global option would be fine with me too.

You show a warning when I try using a different context than I did last time, which is wonderful, but I somehow overlooked it anyway and deployed to prod. Whoops.

I'm using my machine for both local development and deploying to prod, which means I have to switch back and forth all the time right now. Devspace should never use my prod context though, so it would be nice if I could just hardcode the context in `devspace.yaml`.

**Which alternative solutions exist?**  
It appears there's a global flag actually, `--kube-context`, so I can do `devspace --kube-context docker-desktop dev` but that's a little too much typing, and if I forget the flag I'm in trouble.

**Additional context**  
Upon further reflection, I suspect you haven't made this an option in the yaml because the yaml is supposed to be distributed amongst the team whom may have different setups? In that case I propose one of two options:

1. Allow my specify the the kube context in devspace.yaml anyway, for single devs like me or small teams with homogeneous setups. Bigger teams with distinct setups can just not specify the context and ask their devs to pick based on their personal setup.
2. The first time `devspace` is ran, ask me to pick a context. Save this somewhere, probably under that `.devspace` dir you've already got. Re-use this context every time I use `devspace` instead of warning when it's different.

/kind feature

**Comment by FabianKramm** [comment]
@mnpenner thanks for opening this issue! Actually in older versions of devspace we had an option where you could specify the kube context within the devspace.yaml. However we decided to remove it because:
- `devspace.yaml` is distributed among teams with different local configurations and kube context names, which usually results in conflicts.
- It increases confusion because the context in the config was often overlooked and people wondered why the current context isn't used

As a workaround I suggest adding a command for deploying to a specific context like this:
```
commands:
- name: deploy-with-context
  command: devspace deploy --kube-context kubecontext
  description: "This command runs devspace deploy and sets the context to a specific value"
```

If you don't want to add a new command or want to specify it for every command, another option would be to create an .env file for your local configuration with:
```
DEVSPACE_FLAGS=--kube-context=my-context
# Or only for certain commands
DEVSPACE_DEV_FLAGS=--kube-context=my-context
```

When defining the context via .env you can still override it if you provide the flag again to the command:
```
# Will use my-context-2 instead of my-context
DEVSPACE_FLAGS=--kube-context=my-context devspace deploy --kube-context=my-context-2
```

This will append to every command the kube context flag and you don't have to commit the `.env` file, which allows to still distribute the `devspace.yaml` across your team.

**Comment by mnpenner** [comment]
That works well. Thank you 😄
