### ISSUE TITLE
Command to restart container

### ISSUE THREAD

**Issue by tom-acceleratecompliance** [devspace-cloud/devspace#1161]
Firstly, thanks for the amazing tool, it works brilliantly for us.

**Is your feature request related to a problem?**  
We use devspace with Ruby on Rails. Most of the time, the hot code reload works brilliantly and the `onUpload.restartContainer` is set to false. However, when working in rails, it is sometimes necessary to restart the application (such as when changing an initializer).

Restarting the container would achieve this as well, so our current solution involves changing `restartContainer` to true, cancelling and then restarting `devspace dev` before changing the code to trigger the reload, before setting `restartContainer` back to false.

**Which solution do you suggest?**  
A CLI command to perform the exact action that `restartContainer` performs when the code changes.

/kind feature

**Comment by LukasGentele** [comment]
Thanks for opening this issue. That's an interesting case where you want auto-restart disabled but on-demand restarts as user-friendly and quickly as possible. With the current capabilities, you could run `devspace dev -d` but that won't always work because the deployment may not have changed. Another option is `devspace dev -b` which forces a new tag to be built and therefore, it should always restart the containers. However, I get that image building may take a while and is not as user-friend. I actually have the same issue with another application as well but I always did the image rebuilding. But not every team has images which are as cache-optimized as the one I'm working with in this case.

An idea that just came to my mind to make manual restarts easy to trigger: How about a hotkey like pressing "r" or pressing <space key> or something like that which tells devspace to run trigger the hot-reload (aka kill the process pid2 process to that the restart helper kicks in and restarts the application again). We could print a message about this capability before starting the log stream and then just reading the stdin while doing log streaming.

@tom-acceleratecompliance What do you think about this idea?
@FabianKramm Any thoughts on this?

**Comment by tom-acceleratecompliance** [comment]
Hi @LukasGentele - thanks for taking a look at this!
I had attempted to use `devspace dev -d/-b` but ran into the issue you mentioned around how long the container takes to rebuild. I don't know the internals of devspace, but would something like `devspace dev -r` be possible? Expected behaviour being "Start devspace while immediately restarting the container as though `restartContainer` was set to true and a code change had occured" 

This feels very user friendly to me, kill devspace dev with a `control+c`, start again with `devspace dev -r`.

One workaround we did find if we're doing work which requires server restarts frequently is to change the container yaml to just sit and wait:

```yaml
command:
  - tail 
args:
  - "-f"
  - "/dev/null"
```

Then we run `devspace enter` and start the server normally with `puma` or `rails s`. We can just kill and restart the server as needed in that context as required.
To any rails devs reading this, this approach has the added advantage of allowing byebug/pry to work nicely.

**Comment by LukasGentele** [comment]
@tom-acceleratecompliance the flag should be even easier to do.

I know a few teams who use DevSpace using rails. A common pattern is what you described. Instead of opening the terminal in a second window, you can also tell DevSpace to open the terminal instead of opening the log stream. Take a look at dev.interactive for the relevant config options

**Comment by FabianKramm** [comment]
Implemented with v5.1.0
