### ISSUE TITLE
devspace sync uploads unmodified files

### ISSUE THREAD

**Issue by ComaVN** [devspace-cloud/devspace#1177]
**What happened?**
When running `devspace dev`, it starts a container, and immediatly restarts it because the sync process thinks some files have changed and need to be uploaded, even tho the docker image was just built.

The reason seems to be that the file modification time in the docker image differs from the time on the local file system: this is possible, because docker build layer caching actually checks the content of the files: if only the timestamp changed, docker build will just use the cached layer, and that cached layer obviously has the old modification time. Devspace sync then sees the different modification time, and decides to upload the unmodified file anyway.

**What did you expect to happen instead?**  
I expect a freshly built container with the proper `excludePaths` defined in `devspace.yaml` to not require an immediate restart when there have been no actual changes to any files.

I expect the sync process to actually check if a file's content has changed before uploading it, and not *just* look at the file modification time, in the same way that eg. git or the Docker layer caching do this.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
https://github.com/ComaVN/devspace-sync-poc

**Local Environment:**  
- DevSpace Version: 5.0.3
- Operating System: Ubuntu 20.04.1 LTS
- Deployment method: kubectl apply

**Kubernetes Cluster:**  
- Cloud Provider: DevSpace Cloud
- Kubernetes Version: client v1.18.8, server v1.18.6

**Anything else we need to know?**  
The main reason this is problematic for us, is because we're re-compiling our golang code (using delve) every time the container (re)starts.

/kind bug

**Comment by FabianKramm** [comment]
@ComaVN thanks for reporting this issue! Yes you are right, currently we only compare modification times and file sizes initially to determine which files have changed. We opted to do this, since it is a lot faster than comparing actual content checksums of the files. I think what we could think about is that before a file is actually synced and devspace thinks that its changed, that the content checksum is taken of both files and compared again, so that the described problem does not appear anymore.

**Comment by FabianKramm** [comment]
@ComaVN this is implemented in v5.1.0
