### ISSUE TITLE
new behavior with --config file option?

### ISSUE THREAD

**Issue by igoooor** [devspace-cloud/devspace#1249]
**What happened?**
Before updating to 5.5.0 (I don't remember which version I had..) when I would specify a `--config` in a sub directory (e.g. `--config=some/dir/devspace.yaml` devspace would run from my current directory (not from the directory where the file is). So in my devspace.yaml file, `images.<name>.dockerfile` would be in reference of my current directory.
Since I updated to 5.5.0, it seems that `images.<name>.dockerfile` is now in reference to the directory where the devspace.yaml is located.

also the folder `.devspace` created by devspace is now located not in my current directory, but in the directory where the devspace.yaml file is.

I'm not sure if this is a bug, or a new feature. Just to know what to expect in the future.
Sorry if I missed a patch note, I tried to have a look there first.

/kind bug

**Comment by FabianKramm** [comment]
@igoooor thanks for opening this issue! Yes we fixed that in version 5.4.0 (`Fixes an issue where local paths were wrong when using devspace dev --config other-folder/devspace.yaml (#1226)`), because it makes it much easier to specify a `devspace.yaml` where you can assume the relative paths are always relative to the path where the devspace.yaml is in and not where the command is executed. I think this is also the more expected behaviour if you write a `devspace.yaml`

**Comment by igoooor** [comment]
makes sense yes, thanks!
