### ISSUE TITLE
Specify image tag

### ISSUE THREAD

**Issue by michalip** [devspace-cloud/devspace#559]
**What happened?**  
Not able to set the image tag properly . Tried two scenarios below

**What did you expect to happen instead?**  
Expect to be able to specify an image tag for deployment

**How can we reproduce the bug?** (as minimally and precisely as possible)  
	`image name inside devspace.yaml= A.B.C:5000/imagename:version1`
	
	bash-4.2$ devspace dev

```
[info]   Loaded config from devspace.yaml
[info]   Building image 'A.B.C:5000/imagenam:latest' with engine 'docker'
[fatal]  Error building image: Error during image build: Error during image registry authentication: invalid reference format
```

	image name inside devspace.yaml =	A.B.C:5000/imagename
	bash-4.2$ devspace dev
	
```
ujCxYya: digest: sha256:14830b2da76fb52135726c4f4c7f56743b36daeefeb250fa8f1983dd5eab3a2b size: 2832
[info]   Image pushed to registry (A.B.C:5000)
[done] √ Done processing image 'A.B.C:5000/imagename'
[done] √ Deployed helm chart (Release revision: 3)
[done] √ Successfully deployed compname with component
[fatal]  Unable to start portforwarding: Error starting port-forwarding: Unable to list devspace pods: Selected Pod(s) cannot start (Status: ErrImage)
```

```
Events:
  Type     Reason     Age                    From                      Message
  ----     ------     ----                   ----                      -------
  Normal   Scheduled  5m28s                  default-scheduler         Successfully assigned devspace/imagename-7c889d5b8c-kpg8w to server
  Normal   Pulling    4m3s (x4 over 5m27s)   kubelet, server
  pulling image "A.B.C:5000/imagename"
  Warning  Failed     4m3s (x4 over 5m27s)   kubelet, server  Failed to pull image "A.B.C:5000/imagename": rpc error: code = Unknown desc = Error response from daemon: Get https://A.B.C:5000/v2/imagename/manifests/latest: no basic auth credentials
  Warning  Failed     4m3s (x4 over 5m27s)   kubelet, server  Error: ErrImagePull
  Warning  Failed     3m35s (x7 over 5m27s)  kubelet, server  Error: ImagePullBackOff
```

**Local Environment:**  
- Operating System:  linux 
- Deployment method:  kubectl apply

**Kubernetes Cluster:**  
- Cloud Provider: on prem K8s
- Kubernetes Version: 1.13.3

**Anything else we need to know?**  

It would be great if I didnt have to edit devspace.yaml at all - as this will be targeted towards users and I dont want to give them too much overhead 

Thanks Guys

/kind bug

**Comment by FabianKramm** [comment]
@michalip thanks for reporting this issue!  

I think your problem may be a configuration issue. In the first scenario the error is thrown because we don't expect an image name with an already appended image tag (we should definitively improve the error message there). The way devspace works is we create a random tag during image build (or a tag specified by you in the config option `images.name.tag`) and then append this tag during deployment phase in memory to the image name in the kubectl manifests / helm values or component configuration.  

In the second scenario the configuration itself is correct, but I think the problem may be that there is no pull secret for your registry in the cluster. DevSpace can automatically create a pull secret for you (there should be a question during `devspace init`) and attach it to the default service account, but you have to enable this in the configuration, do you have the config option ìmages.name.createPullSecret` on true in the `devspace.yaml`?

**Comment by michalip** [comment]
HI @FabianKramm
Yes I've selected to enable pull secrets but that didnt work either.
What I havent tried though is to create the namespace before hand, and then create the secret there. Both actions manually. This is what I normally do when I create a new namespace. But as I said before, I want to avoid manual work for the users.

What I noticed is that the image is getting pushed o my registry successfully with a random image tag. And then unfortunately it doesn try to pull/deploy the same image tag but tries without a tag ....so docker assumes latest which doesnt exist.

I hope i ve explained it thoroughly :)

**Comment by FabianKramm** [comment]
@michalip Ah okay I see, then my assumption was wrong and the replacement didn't work during deployment for some reason and caused the problem. Could you post your `devspace.yaml` here?

**Comment by FabianKramm** [comment]
@michalip Nevermind, I found the issue it's a problem in the code because of the `:5000` in the registry. I'll fix that real quick and release a new version today.

**Comment by michalip** [comment]
@FabianKramm
Will do, but it will have to wait until Monday. Have a great weekend and thanks for the support

**Comment by michalip** [comment]
@FabianKramm
That's Fantastic !! Cant wait to try it
