### ISSUE TITLE
Accessing the UI/Dashboard

### ISSUE THREAD

**Issue by michalip** [devspace-cloud/devspace#564]
Hello, 

Trying to access the UI/Dashboard for an on premises K8s Cluster.

```
bash-4.2$ devspace connect cluster
[wait] / Logging into cloud provider... (826s)
```
Not sure what it means to log into the cloud provider if I am using on premises K8s cluster with kubectl ...

So far I was able to do `deploy dev /analyze /deploy` , but not able to get the dashboard 

Thanks

**Comment by FabianKramm** [comment]
@michalip thanks for reporting this issue!  

Usually Logging into cloud provider means that DevSpace should open a browser tab with the url [https://app.devspace.cloud/login?cli=true](https://app.devspace.cloud/login?cli=true), if that is not the case you can manually navigate to that link in the browser when devspace prints the message `Logging into cloud provider`.

**Comment by michalip** [comment]
Hi @FabianKramm,
That would be off-premises then. If I understand correctly you are currently developing a full on-premises solution that would also include the dashboard. Currently not available for on-premises, correct?

**Comment by FabianKramm** [comment]
To give a little breakdown what can run where:
- DevSpace CLI which is basically the complete client functionality can be used in every kubernetes hosted either on-premise, in the public cloud or on our platform. The CLI can be used completely independently of any DevSpace Cloud functionality.
- DevSpace Cloud (hosted by us) allows you to connect any kubernetes cluster hosted in public cloud or on premise to the platform (for free), which allows you to create and manage spaces (isolated kubernetes namespaces for developers / testing etc.) over our platform in your cluster you have connected. (We only save an encrypted sa token to your cluster in our database which can be only decrypted via the key locally stored on your computer, this means we can never access your cluster without you sending us the key for any action you perform on your cluster) This allows us to only install a very lightweight control plane in your cluster we need for namespace isolation and domain management and hence makes it easy for you to setup, since all the management components are running in our cluster.
- DevSpace Cloud (hosted by you) basically is a complete on-premise solution, where you host every component of DevSpace Cloud. This version however is currently enterprise only and not for free.

**Comment by LukasGentele** [comment]
@michalip Can we close this issue or do you still experience issues accessing the UI?

**Comment by michalip** [comment]
Closing , thank you
