### ISSUE TITLE
Devspace CLI Error after installing via NPM

### ISSUE THREAD

**Issue by izzatzr** [devspace-cloud/devspace#618]
**What happened?**  

/home/user/.npm-global/bin/devspace: line 7: syntax error near unexpected token `newline'
/home/user/.npm-global/bin/devspace: line 7: `<!DOCTYPE html>'

**How can we reproduce the bug?** (as minimally and precisely as possible)  

npm install -g devspace

**Local Environment:**  
- Operating System: windows | linux | mac

**Anything else we need to know?**  

/kind bug

**Comment by LukasGentele** [comment]
@izzatzr thanks for reporting this! Are you using Linux? Could you send me the output of this command: 
```
npm root -g
```

**Comment by LukasGentele** [comment]
So, this problem occurred because the release has been deleted. I modified the npm install script in a way that it automatically downloads the latest release in case the requested version does not exit anymore. That should fix the issue.

@izzatzr Thanks again for reporting this! You can install devspace using:
```
npm uninstall -g devspace
npm install -g devspace
```

**Comment by izzatzr** [comment]
> So, this problem occurred because the release has been deleted. I modified the npm install script in a way that it automatically downloads the latest release in case the requested version does not exit anymore. That should fix the issue.
> 
> @izzatzr Thanks again for reporting this! You can install devspace using:
> 
> ```
> npm uninstall -g devspace
> npm install -g devspace
> ```

thanks to you man , problem solved
