### ISSUE TITLE
sync: devspace sync command behavior

### ISSUE THREAD

**Issue by FabianKramm** [devspace-cloud/devspace#732]
Currently devspace sync will delete locally not existing files in the remote folder. While this behavior makes sense for `devspace dev` and can be configured with the downloadOnInitialSync flag there is no option for the `devspace sync` command. We should introduce a flag `--download-on-initial-sync` so users are able to configure such behaviour

**Comment by LukasGentele** [comment]
Completely agree. I even think that `--download-on-initial-sync` should be `true` by default because using `false` does not just mean not downloading files, it would also mean deleting remote files if they are not existing locally and that is a very common scenario but deleting the files is very rarely intended.
