### ISSUE TITLE
build: make rebuild behavior configurable

### ISSUE THREAD

**Issue by FabianKramm** [devspace-cloud/devspace#733]
Currently the behavior for rebuilding images is different for `devspace dev` and `devspace deploy`: during `devspace dev` an image is not rebuild if a file in the context of the image has been changed, while during `devspace deploy` the image will be rebuild. However, there are cases when you want to rebuild an image during `devspace dev` e.g. when you are not syncing  any files into that image. 

Hence it makes sense to always rebuild images on context change during `devspace dev` for images that have not a sync path defined.

**Comment by LukasGentele** [comment]
Makes sense to me. However, checking for sync paths might be difficult because some users have just one image and use different entrypoints for different deployments. That means their sync paths cannot use the `imageName` option. Checking for this option might be inflexible for use cases like this one where users mainly use `labelSelector` instead of `imageName`.

**Comment by LukasGentele** [comment]
The implementation via #740 looks good. Making `imageSelector` and `labelSelector` non-exclusive and rather using them jointly for selecting pods solves the issue with using the same image in multiple deployments.
