### ISSUE TITLE
distinguish among pods using same image in dev mode

### ISSUE THREAD

**Issue by shaunc** [devspace-cloud/devspace#851]
**What happened?**  

I have two deployments running from the same image (with different commands): one is a web server, the other a utility image to allow command-line access. When I run `devspace dev` I get a stream of messages of the form:

```
[warn]   Multiple pods with image selector 'factfiber/crane-web-django:59c46897-shauncutts-kvTIqn' found. Using first pod found
```

I presume devspace is trying to match up running pods to deployments based on image. However, this is not unique in my case. I presume this is because of sync or auto reload issues. I guess for auto reload the should both be reloaded. For sync I only specify one deployment -- if the problem is sync, I guess no need to used the image name, but a selector based on (e.g) "app.kubernetes.io/component"?

**What did you expect to happen instead?**  

No messages and sync/reload working as specified

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Create two deployments from one image and specify sync & autoreload

**Local Environment:**  
- Operating System: windows | linux | mac
- Deployment method: helm | kubectl apply

Mac, helm

**Kubernetes Cluster:**  
- Cloud Provider: google | aws | azure | DevSpace Cloud | DevSpace Cloud Enterprise | other
- Kubernetes Version: [use `kubectl version`]

local kubernetes via docker for Mac ;

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@shaunc thanks for opening this issue! The error message will be shown once for every sync / port-forwarding configuration you have that has potentially multiple pods pointing to the same image name. The correct solution for this would be to use the config option `labelSelector` instead of `imageName`.  

However, since you mentioned that you see a bunch of these messages together, it seems that the port-forwarding or sync are restarting unexpectedly often, which is probably the real issue here. Could you check the `.devspace/logs/sync.log` if you find any error messages on why the sync might be restarting? Is neither of port-forwarding and sync working for you correctly? I just tested your issue with the quickstart example and it works for me with multiple deployments pointing to the same image name, the sync and port forwarding correctly restarts without a message, I just receive one warning per configuration in the beginning.

**Comment by shaunc** [comment]
Ok -- I had a typo in one of the paths to sync to, which caused sync fail and repeat. (And it would eventually have an error such as:
`[error]  Error restarting sync: start sync: create pipe: pipe: too many open files. See more logs at .devspace/logs/sync.log`)

In the best case if there is a problem like a non-existent directory in container it should clean up on failure and also only retry a bounded # of times in a row before stopping attempted sync for given deployment. However, that is a much milder issue -- I don't know if you want an issue for that (and whether it should be this one)? For the moment, closing.

**Comment by FabianKramm** [comment]
@shaunc thanks for pointing that out! I added a fix for the error you mentioned (the sync is now properly cleaning up those pipes) and it will fail instead of trying to reconnect if the folder in the container does not exist!

**Comment by shaunc** [comment]
Ah -- great. NB I had thought that it could be possible that the user wants to sync with a directory which doesn't exist at first, but is created by the app on startup. That is why I mentioned fail after bounded # of retries. Still, perhaps that is an edge case with no actual audience. :)

**Comment by mnpenner** [comment]
Would it be possible to change this behavior so that it syncs to all pods with the given image?

I actually have three: my app, a worker, and a cronjob.
