### ISSUE TITLE
Sync crash when a targeted pod dies

### ISSUE THREAD

**Issue by dsebastien** [devspace-cloud/devspace#885]
**What happened?**  
I've configured devspace sync to sync to multiple pods based on labels.
The sync starts normally and files are synchronized.
After a while, one of the pod dies or is killed manually (whatever the reason).
At this point, devspace sync seems to die because it lost contact with one of the targeted pods.

**What did you expect to happen instead?** 
I would've liked for sync to just keep going and try to find new pods  matching the labels to sync files to those.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Configure devspace sync to sync to (at least 2?) pods based on label X. Start devspace, let it do what it does. Once stable, kill one of the 'X' labeled pods.

**Local Environment:**  
Lnux
- OS: Linux
- Deployment method: kubectl apply

**Kubernetes Cluster:**  
- Minikube
- Kubernetes Version: 1.17.0

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@dsebastien thanks for opening this issue! Currently `devspace sync` is designed to only have one target pod & container to sync to/from. Multiple targets would add considerable complexity (especially if you not only want to upload files to multiple pods), but of course you could just run `devspace sync` multiple times (however downloading from multiple pods into the same folder should be avoided, because this can lead to potential endless loops). Starting `devspace sync` in only upload or download mode is coming with the next release.

When the pod that is synced to is killed or removed for whatever reason, `devspace sync` should try to reconnect to a pod with the same label selector / pod name etc., this should work with the newest DevSpace version. Is there any error message when DevSpace loses contact?

**Comment by FabianKramm** [comment]
Should be fixed in v4.4.0

**Comment by irfani** [comment]
@FabianKramm I have the same sync problem after upgrading to v4.4. The issue was solved when I switch it back to v4.3.5

log message :
{"level":"error","msg":"Sync Error on D:\\Dev\\framework: Sync - connection lost to pod dev/app-0:  command terminated with exit code 139","time":"2020-01-24T09:43:55+07:00"}
{"level":"info","msg":"Sync stopped","time":"2020-01-24T09:43:55+07:00"}

**Comment by dsebastien** [comment]
I understand the current design of devspace sync, but I think that it would be nice for it to also support a one-way sync towards multiple pods.

In my case I have the following situation: two different pods run the same base image, which is basically the dev stage of my app's image. That image includes all the shared development dependencies and allows to run either the back-end or the front-end. For it to use the latest code, I need to sync my local files to both of these containers (one way sync towards the pods).

Both pods have the same base labels, which we use in the DevSpace sync config.

So far this setup is working fine, apart from the case where we need (for whatever reason) to kill one of the pods. In that case our only solution is to stop/restart sync.

I can understand if you don't want to incorporate support for this specific scenario, but I do hope that the basic capability to do a one-way sync to multiple pods will continue to work.

Thanks again, Sébastien.

**Comment by FabianKramm** [comment]
@dsebastien I understand your use case, however what does prevent you to add a different label to one of these base image pods?
