### ISSUE TITLE
Prevent multiple image definitions with the same image name

### ISSUE THREAD

**Issue by FlorianKutz** [devspace-cloud/devspace#886]
**Is your feature request related to a problem?**  
In the `devspace.yaml` it is currently possible to specify the same image repository (`images.*.image`)  for multiple image definitions. We should prevent this or atleast show a warning in the config validation, because this can lead to unexpected behavior during deployment.

**Which solution do you suggest?**  
To avoid issues with this, add a check in validate. When the config is loaded and two images have the same image repository, either break up or at the very least print a warning to inform the user.

**Which alternative solutions exist?**  

**Additional context**  

/kind feature

**Comment by alexrimlin** [comment]
To anyone struggling with this.
In my case I'm building multi-arch images with Kaniko and parallel execution with the same 'image' isn't possible due to [this check](https://github.com/devspace-sh/devspace/blob/419d97eaa442b843f7be4260ad6a0db188759c6d/pkg/devspace/config/versions/validate.go#L342). 
I've replaced this line with `fmt.Printf("WARNING: images.*.image '%s' is used multiple times\n", imageConf.Image)`, built the binary and it works without any issues. 
I'm new to Go so I'm not sure if I should create a pull request with these changes.
