### ISSUE TITLE
DevSpace should quit and display error message if it can't open ingress

### ISSUE THREAD

**Issue by jmarbach** [devspace-cloud/devspace#894]
**What happened?**  

For my production deployment I added a custom host to the ingress with the option `tls: true`:
```
ingress:
        rules:
        - host: customdomain.com
          tls: true
```

I deployed my application and then ran `devspace open`. DevSpace continued to wait to open the ingress after it was not able to initially open the application at the ingress.

The command `devspace analyze` command indicated that nothing was wrong with the application's configuration.

[View a screen recording](https://drive.google.com/file/d/1Wf4yIA3PTgMPLFDfkEa7Br7bybyGTP_5/view?usp=sharing)

**What did you expect to happen instead?**  

I expected the `devspace open` command to open the application at the custom host.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Add a custom host to the ingress and specify the option `tls: true`, e.g.

```
ingress:
        rules:
        - host: customdomain.com
          tls: true
```

**Local Environment:**  
- Operating System: mac
- Deployment method: helm 

**Kubernetes Cluster:**  
- Cloud Provider: DigitalOcean
- Kubernetes Version:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-15T15:50:38Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**  

/kind bug

**Comment by LukasGentele** [comment]
@jmarbach Thanks for opening this issue and for the screen cast (that was really helpful!). 

Generally this what happens: `devspace open` tries to connect to the custom domain via HTTPS (because it detects that the ingress is configured to use TLS as defined via `tls: true`). However, in order for HTTPS to actually work for the ingress, your cluster needs to provision a valid SSL certificate for the ingress and save it as a Kubernetes secret. Setting `tls: true` just configures the ingress to use a (default) secret name (different secret name could be provisioned via `tls: my-tls-secret` instead of `true`) but if this secret (which must contain the SSL certificate) does **not** exist within the namespace of this ingress, the HTTPS connection will not be possible. So `devspace open` sees that the ingress is configured to use TLS but it does not work (connection fails) which results in DevSpace indefinitely trying to connect, back-off, connect, back-off etc.

In your specific case: Is the DO cluster you are deploying to connected to DevSpace Cloud? 

A: If yes, you can create the certificate in the UI of DevSpace Cloud via `Spaces > [space-name] > Network > Maximize-Icon of the Ingress > Enable TLS (next to hostname)`. In the future, this will happen automatically when deploying the component Helm chart using `tls: true` but currently this is not possible due to a limitation in the user restrictions for connected clusters. @FabianKramm: Do we have an ETA for a fix for this, yet?

B: If you are not using DevSpace Cloud, you should deploy `cert-manager` and create a Certificate resource manually or by adding it as a manifest or helm chart deployment in your `devspace.yaml`.

**Comment by jmarbach** [comment]
Hey @LukasGentele,

Thanks for looking into this. In this case the DO cluster is connected to DevSpace cloud and I had already installed the certificate by following the same path you indicated. I also installed a SSL certificate on my DO load balancer. Maybe I have to use the SSL cert from the load balancer as a string instead of the boolean `true` which generates an SSL cert automatically? I don't quite understand.

**Comment by LukasGentele** [comment]
@jmarbach Yes, you should be able to set `ingress.tls: [SECRET_NAME]` in devspace.yaml so that it matches the name of the secret for your SSL certificate in the same namespace. You can always check with `kubectl get ing -o yaml` what the `tls[*].secretName` says and check with `kubectl get secrets` if this secret actually exists and contains your SSL cert. Let me know if that is matching but you're still not able to access the domain via HTTPS.

**Comment by LukasGentele** [comment]
The issue with this was a missing annotation in the ingress. It should be fixed in the newest release. However, `ingress.rules[].tls` has been replaced with `ingress.tls`. Setting this option to true will actually lead to cert-manager provision the certificate and storing it in the appropriate secret. Please feel free to reopen if there are further issues related to the tls settings of components.
