### ISSUE TITLE
Skip init question for registry if current-context is docker-desktop

### ISSUE THREAD

**Issue by BLoeT** [devspace-cloud/devspace#907]
**What happened?**  
devspace init ask for registry to push for local context

**What did you expect to happen instead?**  
skip question 

**How can we reproduce the bug?** (as minimally and precisely as possible)  
devspace init with docker-desktop context in project path on mac

**Local Environment:**  
- Operating System: mac

**Kubernetes Cluster:**  
- Cloud Provider: docker-desktop
- Kubernetes Version: [use `kubectl version`]
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:07Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Anything else we need to know?**  

/kind bug

**Comment by LukasGentele** [comment]
@BLoeT Thanks for opening this issue. I think that is a smart idea to make init better for local clusters. I still think we should ask the question in case users want to make their image accessible. I think it could be odd if the question does not come up depending on the context. I still think you have a valid point. I think a solution would be to add an option "Skip image push (for local clusters)" or something to the picker, so that users can skip this step very easily. What do you think?

**Comment by BLoeT** [comment]
wow thanks for fast reply.

yeah i think this option would be perfekt and very useful :)

**Comment by FabianKramm** [comment]
This is fixed and will be released today
