### ISSUE TITLE
docs: new doc website lacks documentation of service and ingress

### ISSUE THREAD

**Issue by shaunc** [devspace-cloud/devspace#974]
**What happened?**  

Wanted to review "ingress" configuration info, but seems to be missing.

**What did you expect to happen instead?**  

**How can we reproduce the bug?** (as minimally and precisely as possible)  

**Local Environment:**  
- DevSpace Version: [use `devspace --version`]
- Operating System: windows | linux | mac
- Deployment method: helm | kubectl apply

**Kubernetes Cluster:**  
- Cloud Provider: google | aws | azure | DevSpace Cloud | DevSpace Cloud Enterprise | other
- Kubernetes Version: [use `kubectl version`]

**Anything else we need to know?**  

Hmm... you had "search" -- right? Can we re-enable?

/kind bug

**Comment by LukasGentele** [comment]
There is actually a separate documentation site for this now: https://devspace.sh/component-chart/docs/introduction

The reason for this is that the component-chart is independent of DevSpace, i.e. it can be used with helm directly, and it also has an independent release cycle, i.e. the versions are not the same and the code is also in a different GitHub repository. There are a couple of links in the DevSpace CLI docs which point to the docs of the component-chart. Maybe, I need to add a couple more to make it more obvious ;)

PS: Search had to be disabled because Algolia needs 24h to index a page after the URL has changed. I will enable search on all 3 docs sites (cli, cloud, component-chart) later today, when the index should be filled again.

**Comment by shaunc** [comment]
Ok -- great. Yes ... a couple more links please! :)
